# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/cferr/Desktop/Laboratorio CEP/P1/fifo_board_test/fifo_board_test.cache/wt} [current_project]
set_property parent.project_path {C:/Users/cferr/Desktop/Laboratorio CEP/P1/fifo_board_test/fifo_board_test.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/cferr/Desktop/Laboratorio CEP/P1/fifo_board_test/fifo_board_test.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/cferr/Desktop/fifo_placa_def/fifo_placa_def.srcs/sources_1/new/D_flip_flop_ce_pop.vhd
  C:/Users/cferr/Desktop/fifo_placa_def/fifo_placa_def.srcs/sources_1/new/D_flip_flop_ce_push.vhd
  C:/Users/cferr/Desktop/fifo_placa_def/fifo_placa_def.srcs/sources_1/new/Decodificador_binario_a_7_segmentos.vhd
  C:/Users/cferr/Desktop/fifo_placa_def/fifo_placa_def.srcs/sources_1/new/Generador_CE_1KHz.vhd
  C:/Users/cferr/Desktop/fifo_placa_def/fifo_placa_def.srcs/sources_1/new/Inst_N_bits_ascending_counter_ptr_read.vhd
  C:/Users/cferr/Desktop/fifo_placa_def/fifo_placa_def.srcs/sources_1/new/Inst_N_bits_ascending_counter_ptr_write.vhd
  C:/Users/cferr/Desktop/fifo_placa_def/fifo_placa_def.srcs/sources_1/new/ctrl_fifo_predictivo.vhd
  C:/Users/cferr/Desktop/fifo_placa_def/fifo_placa_def.srcs/sources_1/new/detector_flancos_pop.vhd
  C:/Users/cferr/Desktop/fifo_placa_def/fifo_placa_def.srcs/sources_1/new/detector_flancos_push.vhd
  C:/Users/cferr/Desktop/fifo_placa_def/fifo_placa_def.srcs/sources_1/new/dual_port_distributed_ram_async_read.vhd
  C:/Users/cferr/Desktop/fifo_placa_def/fifo_placa_def.srcs/sources_1/new/empty_fifo_flip_flop.vhd
  C:/Users/cferr/Desktop/fifo_placa_def/fifo_placa_def.srcs/sources_1/new/full_fifo_flip_flop.vhd
  C:/Users/cferr/Desktop/fifo_placa_def/fifo_placa_def.srcs/sources_1/new/visualizador.vhd
  C:/Users/cferr/Desktop/fifo_placa_def/fifo_placa_def.srcs/sources_1/new/fifo_16_byte_distributted_RAM.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/cferr/Desktop/fifo_placa_def/fifo_placa_def.srcs/constrs_1/new/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/cferr/Desktop/fifo_placa_def/fifo_placa_def.srcs/constrs_1/new/Nexys4DDR_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_fifo_16_byte_disttributed_RAM -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_fifo_16_byte_disttributed_RAM.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_fifo_16_byte_disttributed_RAM_utilization_synth.rpt -pb top_fifo_16_byte_disttributed_RAM_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
